name: openspot
description: "An open-source music player powered by Spotify and YouTube."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: 3.6.0
  flutter: 3.27.1

dependencies:
  back_button_interceptor: ^8.0.3
  cached_network_image: ^3.4.1
  dynamic_color: ^1.7.0
  easy_load_more: ^1.1.0
  flutter:
    sdk: flutter
  flutter_js:
    git:
      url: https://github.com/ItsPi3141/flutter_js.git
      ref: master
  flutter_timezone: ^4.0.0
  http: ^1.2.2
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.14
  mdi: ^5.0.0-nullsafety.0
  package_info_plus: ^8.1.2
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
