name: openspot
description: "An open-source music player powered by Spotify and YouTube."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: 3.3.4
  flutter: 3.19.6

dependencies:
  cached_network_image: ^3.3.1
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_timezone: ^1.0.8
  http: ^1.2.1
  mdi: ^5.0.0-nullsafety.0
  package_info_plus: ^7.0.0
  provider: ^6.1.2
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
