name: openspot
description: "An open-source music player powered by Spotify and YouTube."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: 3.4.3
  flutter: 3.22.2

dependencies:
  cached_network_image: ^3.3.1
  dynamic_color: ^1.7.0
  easy_load_more: ^1.1.0
  flutter:
    sdk: flutter
  flutter_js:
    git:
      url: https://github.com/ItsPi3141/flutter_js.git
      ref: master
  flutter_timezone: ^1.0.8
  http: ^1.2.1
  just_audio: ^0.9.38
  mdi: ^5.0.0-nullsafety.0
  package_info_plus: ^8.0.0
  provider: ^6.1.2
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
